//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.18052
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Dieser Quellcode wurde automatisch generiert von xsd, Version=4.0.30319.17929.
// 
namespace Ifc4.Pset
{
    using System.Xml.Serialization;


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class PropertySetDef : object, System.ComponentModel.INotifyPropertyChanged
    {

        private PropertySetDefIfcVersion ifcVersionField;

        private string nameField;

        private string definitionField;

        private string applicabilityField;

        private string[] applicableClassesField;

        private string applicableTypeValueField;

        private PropertyDef[] propertyDefsField;

        private PropertySetDefPsetDefinitionAlias[] psetDefinitionAliasesField;

        private string ifdguidField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public PropertySetDefIfcVersion IfcVersion
        {
            get
            {
                return this.ifcVersionField;
            }
            set
            {
                this.ifcVersionField = value;
                this.RaisePropertyChanged("IfcVersion");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public string Definition
        {
            get
            {
                return this.definitionField;
            }
            set
            {
                this.definitionField = value;
                this.RaisePropertyChanged("Definition");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public string Applicability
        {
            get
            {
                return this.applicabilityField;
            }
            set
            {
                this.applicabilityField = value;
                this.RaisePropertyChanged("Applicability");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order = 4)]
        [System.Xml.Serialization.XmlArrayItemAttribute("ClassName", IsNullable = false)]
        public string[] ApplicableClasses
        {
            get
            {
                return this.applicableClassesField;
            }
            set
            {
                this.applicableClassesField = value;
                this.RaisePropertyChanged("ApplicableClasses");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 5)]
        public string ApplicableTypeValue
        {
            get
            {
                return this.applicableTypeValueField;
            }
            set
            {
                this.applicableTypeValueField = value;
                this.RaisePropertyChanged("ApplicableTypeValue");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order = 6)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable = false)]
        public PropertyDef[] PropertyDefs
        {
            get
            {
                return this.propertyDefsField;
            }
            set
            {
                this.propertyDefsField = value;
                this.RaisePropertyChanged("PropertyDefs");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order = 7)]
        [System.Xml.Serialization.XmlArrayItemAttribute("PsetDefinitionAlias", IsNullable = false)]
        public PropertySetDefPsetDefinitionAlias[] PsetDefinitionAliases
        {
            get
            {
                return this.psetDefinitionAliasesField;
            }
            set
            {
                this.psetDefinitionAliasesField = value;
                this.RaisePropertyChanged("PsetDefinitionAliases");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ifdguid
        {
            get
            {
                return this.ifdguidField;
            }
            set
            {
                this.ifdguidField = value;
                this.RaisePropertyChanged("ifdguid");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class PropertySetDefIfcVersion : object, System.ComponentModel.INotifyPropertyChanged
    {

        private string versionField;

        private string schemaField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
                this.RaisePropertyChanged("version");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string schema
        {
            get
            {
                return this.schemaField;
            }
            set
            {
                this.schemaField = value;
                this.RaisePropertyChanged("schema");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReferenceSelect : object, System.ComponentModel.INotifyPropertyChanged
    {

        private ReferenceSelectReftype reftypeField;

        private bool reftypeFieldSpecified;

        private string guidField;

        private string uRLField;

        private string librarynameField;

        private string sectionrefField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ReferenceSelectReftype reftype
        {
            get
            {
                return this.reftypeField;
            }
            set
            {
                this.reftypeField = value;
                this.RaisePropertyChanged("reftype");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool reftypeSpecified
        {
            get
            {
                return this.reftypeFieldSpecified;
            }
            set
            {
                this.reftypeFieldSpecified = value;
                this.RaisePropertyChanged("reftypeSpecified");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string guid
        {
            get
            {
                return this.guidField;
            }
            set
            {
                this.guidField = value;
                this.RaisePropertyChanged("guid");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string URL
        {
            get
            {
                return this.uRLField;
            }
            set
            {
                this.uRLField = value;
                this.RaisePropertyChanged("URL");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string libraryname
        {
            get
            {
                return this.librarynameField;
            }
            set
            {
                this.librarynameField = value;
                this.RaisePropertyChanged("libraryname");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string sectionref
        {
            get
            {
                return this.sectionrefField;
            }
            set
            {
                this.sectionrefField = value;
                this.RaisePropertyChanged("sectionref");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public enum ReferenceSelectReftype
    {

        /// <remarks/>
        IfcMaterialDefinition,

        /// <remarks/>
        IfcPerson,

        /// <remarks/>
        IfcOrganization,

        /// <remarks/>
        IfcPersonAndOrganization,

        /// <remarks/>
        IfcExternalReference,

        /// <remarks/>
        IfcTimeSeries,

        /// <remarks/>
        IfcAddress,

        /// <remarks/>
        IfcAppliedValue,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Values : object, System.ComponentModel.INotifyPropertyChanged
    {

        private string[] valueItemField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ValueItem", Order = 0)]
        public string[] ValueItem
        {
            get
            {
                return this.valueItemField;
            }
            set
            {
                this.valueItemField = value;
                this.RaisePropertyChanged("ValueItem");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UnitType : object, System.ComponentModel.INotifyPropertyChanged
    {

        private UnitTypeType typeField;

        private string currencytypeField;

        public UnitType()
        {
            this.typeField = UnitTypeType.USERDEFINED;
            this.currencytypeField = "USERDEFINED";
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(UnitTypeType.USERDEFINED)]
        public UnitTypeType type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
                this.RaisePropertyChanged("type");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("USERDEFINED")]
        public string currencytype
        {
            get
            {
                return this.currencytypeField;
            }
            set
            {
                this.currencytypeField = value;
                this.RaisePropertyChanged("currencytype");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public enum UnitTypeType
    {

        /// <remarks/>
        ANGULARVELOCITYUNIT,

        /// <remarks/>
        COMPOUNDPLANEANGLEUNIT,

        /// <remarks/>
        DYNAMICVISCOSITYUNIT,

        /// <remarks/>
        HEATFLUXDENSITYUNIT,

        /// <remarks/>
        INTEGERCOUNTRATEUNIT,

        /// <remarks/>
        ISOTHERMALMOISTURECAPACITYUNIT,

        /// <remarks/>
        KINEMATICVISCOSITYUNIT,

        /// <remarks/>
        LINEARVELOCITYUNIT,

        /// <remarks/>
        MASSDENSITYUNIT,

        /// <remarks/>
        MASSFLOWRATEUNIT,

        /// <remarks/>
        MOISTUREDIFFUSIVITYUNIT,

        /// <remarks/>
        MOLECULARWEIGHTUNIT,

        /// <remarks/>
        SPECIFICHEATCAPACITYUNIT,

        /// <remarks/>
        THERMALADMITTANCEUNIT,

        /// <remarks/>
        THERMALCONDUCTANCEUNIT,

        /// <remarks/>
        THERMALRESISTANCEUNIT,

        /// <remarks/>
        THERMALTRANSMITTANCEUNIT,

        /// <remarks/>
        VAPORPERMEABILITYUNIT,

        /// <remarks/>
        VOLUMETRICFLOWRATEUNIT,

        /// <remarks/>
        ROTATIONALFREQUENCYUNIT,

        /// <remarks/>
        TORQUEUNIT,

        /// <remarks/>
        MOMENTOFINERTIAUNIT,

        /// <remarks/>
        LINEARMOMENTUNIT,

        /// <remarks/>
        LINEARFORCEUNIT,

        /// <remarks/>
        PLANARFORCEUNIT,

        /// <remarks/>
        MODULUSOFELASTICITYUNIT,

        /// <remarks/>
        SHEARMODULUSUNIT,

        /// <remarks/>
        LINEARSTIFFNESSUNIT,

        /// <remarks/>
        ROTATIONALSTIFFNESSUNIT,

        /// <remarks/>
        MODULUSOFSUBGRADEREACTIONUNIT,

        /// <remarks/>
        ACCELERATIONUNIT,

        /// <remarks/>
        CURVATUREUNIT,

        /// <remarks/>
        HEATINGVALUEUNIT,

        /// <remarks/>
        IONCONCENTRATIONUNIT,

        /// <remarks/>
        LUMINOUSINTENSITYDISTRIBUTIONUNIT,

        /// <remarks/>
        MASSPERLENGTHUNIT,

        /// <remarks/>
        MODULUSOFLINEARSUBGRADEREACTIONUNIT,

        /// <remarks/>
        MODULUSOFROTATIONALSUBGRADEREACTIONUNIT,

        /// <remarks/>
        PHUNIT,

        /// <remarks/>
        ROTATIONALMASSUNIT,

        /// <remarks/>
        SECTIONAREAINTEGRALUNIT,

        /// <remarks/>
        SECTIONMODULUSUNIT,

        /// <remarks/>
        SOUNDPOWERUNIT,

        /// <remarks/>
        SOUNDPRESSUREUNIT,

        /// <remarks/>
        TEMPERATUREGRADIENTUNIT,

        /// <remarks/>
        TEMPERATURERATEOFCHANGE,

        /// <remarks/>
        THERMALEXPANSIONCOEFFICIENTUNIT,

        /// <remarks/>
        WARPINGCONSTANTUNIT,

        /// <remarks/>
        WARPINGMOMENTUNIT,

        /// <remarks/>
        ABSORBEDDOSEUNIT,

        /// <remarks/>
        AMOUNTOFSUBSTANCEUNIT,

        /// <remarks/>
        AREAUNIT,

        /// <remarks/>
        DOSEEQUIVALENTUNIT,

        /// <remarks/>
        ELECTRICCAPACITANCEUNIT,

        /// <remarks/>
        ELECTRICCHARGEUNIT,

        /// <remarks/>
        ELECTRICCONDUCTANCEUNIT,

        /// <remarks/>
        ELECTRICCURRENTUNIT,

        /// <remarks/>
        ELECTRICRESISTANCEUNIT,

        /// <remarks/>
        ELECTRICVOLTAGEUNIT,

        /// <remarks/>
        ENERGYUNIT,

        /// <remarks/>
        FORCEUNIT,

        /// <remarks/>
        FREQUENCYUNIT,

        /// <remarks/>
        ILLUMINANCEUNIT,

        /// <remarks/>
        INDUCTANCEUNIT,

        /// <remarks/>
        LENGTHUNIT,

        /// <remarks/>
        LUMINOUSFLUXUNIT,

        /// <remarks/>
        LUMINOUSINTENSITYUNIT,

        /// <remarks/>
        MAGNETICFLUXDENSITYUNIT,

        /// <remarks/>
        MAGNETICFLUXUNIT,

        /// <remarks/>
        MASSUNIT,

        /// <remarks/>
        PLANEANGLEUNIT,

        /// <remarks/>
        POWERUNIT,

        /// <remarks/>
        PRESSUREUNIT,

        /// <remarks/>
        RADIOACTIVITYUNIT,

        /// <remarks/>
        SOLIDANGLEUNIT,

        /// <remarks/>
        THERMODYNAMICTEMPERATUREUNIT,

        /// <remarks/>
        TIMEUNIT,

        /// <remarks/>
        VOLUMEUNIT,

        /// <remarks/>
        USERDEFINED,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("")]
        Item,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DataType : object, System.ComponentModel.INotifyPropertyChanged
    {

        private DataTypeType typeField;

        public DataType()
        {
            this.typeField = DataTypeType.IfcText;
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(DataTypeType.IfcText)]
        public DataTypeType type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
                this.RaisePropertyChanged("type");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public enum DataTypeType
    {

        /// <remarks/>
        IfcVolumeMeasure,

        /// <remarks/>
        IfcTimeMeasure,

        /// <remarks/>
        IfcThermodynamicTemperatureMeasure,

        /// <remarks/>
        IfcSolidAngleMeasure,

        /// <remarks/>
        IfcPositiveRatioMeasure,

        /// <remarks/>
        IfcRatioMeasure,

        /// <remarks/>
        IfcPositivePlaneAngleMeasure,

        /// <remarks/>
        IfcPlaneAngleMeasure,

        /// <remarks/>
        IfcParameterValue,

        /// <remarks/>
        IfcNumericMeasure,

        /// <remarks/>
        IfcMassMeasure,

        /// <remarks/>
        IfcPositiveLengthMeasure,

        /// <remarks/>
        IfcLengthMeasure,

        /// <remarks/>
        IfcElectricCurrentMeasure,

        /// <remarks/>
        IfcDescriptiveMeasure,

        /// <remarks/>
        IfcCountMeasure,

        /// <remarks/>
        IfcContextDependentMeasure,

        /// <remarks/>
        IfcAreaMeasure,

        /// <remarks/>
        IfcAmountOfSubstanceMeasure,

        /// <remarks/>
        IfcLuminousIntensityMeasure,

        /// <remarks/>
        IfcNormalisedRatioMeasure,

        /// <remarks/>
        IfcComplexNumber,

        /// <remarks/>
        IfcNonNegativeLengthMeasure,

        /// <remarks/>
        IfcInteger,

        /// <remarks/>
        IfcReal,

        /// <remarks/>
        IfcBoolean,

        /// <remarks/>
        IfcIdentifier,

        /// <remarks/>
        IfcText,

        /// <remarks/>
        IfcLabel,

        /// <remarks/>
        IfcLogical,

        /// <remarks/>
        IfcDateTime,

        /// <remarks/>
        IfcDate,

        /// <remarks/>
        IfcTime,

        /// <remarks/>
        IfcDuration,

        /// <remarks/>
        IfcVolumetricFlowRateMeasure,

        /// <remarks/>
        IfcTimeStamp,

        /// <remarks/>
        IfcThermalTransmittanceMeasure,

        /// <remarks/>
        IfcThermalResistanceMeasure,

        /// <remarks/>
        IfcThermalAdmittanceMeasure,

        /// <remarks/>
        IfcPressureMeasure,

        /// <remarks/>
        IfcPowerMeasure,

        /// <remarks/>
        IfcMassFlowRateMeasure,

        /// <remarks/>
        IfcMassDensityMeasure,

        /// <remarks/>
        IfcLinearVelocityMeasure,

        /// <remarks/>
        IfcKinematicViscosityMeasure,

        /// <remarks/>
        IfcIntegerCountRateMeasure,

        /// <remarks/>
        IfcHeatFluxDensityMeasure,

        /// <remarks/>
        IfcFrequencyMeasure,

        /// <remarks/>
        IfcEnergyMeasure,

        /// <remarks/>
        IfcElectricVoltageMeasure,

        /// <remarks/>
        IfcDynamicViscosityMeasure,

        /// <remarks/>
        IfcCompoundPlaneAngleMeasure,

        /// <remarks/>
        IfcAngularVelocityMeasure,

        /// <remarks/>
        IfcThermalConductivityMeasure,

        /// <remarks/>
        IfcMolecularWeightMeasure,

        /// <remarks/>
        IfcVaporPermeabilityMeasure,

        /// <remarks/>
        IfcMoistureDiffusivityMeasure,

        /// <remarks/>
        IfcIsothermalMoistureCapacityMeasure,

        /// <remarks/>
        IfcSpecificHeatCapacityMeasure,

        /// <remarks/>
        IfcMonetaryMeasure,

        /// <remarks/>
        IfcMagneticFluxDensityMeasure,

        /// <remarks/>
        IfcMagneticFluxMeasure,

        /// <remarks/>
        IfcLuminousFluxMeasure,

        /// <remarks/>
        IfcForceMeasure,

        /// <remarks/>
        IfcInductanceMeasure,

        /// <remarks/>
        IfcIlluminanceMeasure,

        /// <remarks/>
        IfcElectricResistanceMeasure,

        /// <remarks/>
        IfcElectricConductanceMeasure,

        /// <remarks/>
        IfcElectricChargeMeasure,

        /// <remarks/>
        IfcDoseEquivalentMeasure,

        /// <remarks/>
        IfcElectricCapacitanceMeasure,

        /// <remarks/>
        IfcAbsorbedDoseMeasure,

        /// <remarks/>
        IfcRadioActivityMeasure,

        /// <remarks/>
        IfcRotationalFrequencyMeasure,

        /// <remarks/>
        IfcTorqueMeasure,

        /// <remarks/>
        IfcAccelerationMeasure,

        /// <remarks/>
        IfcLinearForceMeasure,

        /// <remarks/>
        IfcLinearStiffnessMeasure,

        /// <remarks/>
        IfcModulusOfSubgradeReactionMeasure,

        /// <remarks/>
        IfcModulusOfElasticityMeasure,

        /// <remarks/>
        IfcMomentOfInertiaMeasure,

        /// <remarks/>
        IfcPlanarForceMeasure,

        /// <remarks/>
        IfcRotationalStiffnessMeasure,

        /// <remarks/>
        IfcShearModulusMeasure,

        /// <remarks/>
        IfcLinearMomentMeasure,

        /// <remarks/>
        IfcLuminousIntensityDistributionMeasure,

        /// <remarks/>
        IfcCurvatureMeasure,

        /// <remarks/>
        IfcMassPerLengthMeasure,

        /// <remarks/>
        IfcModulusOfLinearSubgradeReactionMeasure,

        /// <remarks/>
        IfcModulusOfRotationalSubgradeReactionMeasure,

        /// <remarks/>
        IfcRotationalMassMeasure,

        /// <remarks/>
        IfcSectionalAreaIntegralMeasure,

        /// <remarks/>
        IfcSectionModulusMeasure,

        /// <remarks/>
        IfcTemperatureGradientMeasure,

        /// <remarks/>
        IfcThermalExpansionCoefficientMeasure,

        /// <remarks/>
        IfcWarpingConstantMeasure,

        /// <remarks/>
        IfcWarpingMomentMeasure,

        /// <remarks/>
        IfcSoundPowerMeasure,

        /// <remarks/>
        IfcSoundPressureMeasure,

        /// <remarks/>
        IfcHeatingValueMeasure,

        /// <remarks/>
        IfcPHMeasure,

        /// <remarks/>
        IfcIonConcentrationMeasure,

        /// <remarks/>
        IfcTemperatureRateOfChangeMeasure,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PropertyType : object, System.ComponentModel.INotifyPropertyChanged
    {

        private object itemField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TypeComplexProperty", typeof(PropertyTypeTypeComplexProperty), Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute("TypePropertyBoundedValue", typeof(PropertyTypeTypePropertyBoundedValue), Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute("TypePropertyEnumeratedValue", typeof(PropertyTypeTypePropertyEnumeratedValue), Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute("TypePropertyListValue", typeof(PropertyTypeTypePropertyListValue), Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute("TypePropertyReferenceValue", typeof(PropertyTypeTypePropertyReferenceValue), Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute("TypePropertySingleValue", typeof(PropertyTypeTypePropertySingleValue), Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute("TypePropertyTableValue", typeof(PropertyTypeTypePropertyTableValue), Order = 0)]
        public object Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
                this.RaisePropertyChanged("Item");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class PropertyTypeTypeComplexProperty : object, System.ComponentModel.INotifyPropertyChanged
    {

        private PropertyDef[] propertyDefField;

        private string nameField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PropertyDef", Order = 0)]
        public PropertyDef[] PropertyDef
        {
            get
            {
                return this.propertyDefField;
            }
            set
            {
                this.propertyDefField = value;
                this.RaisePropertyChanged("PropertyDef");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PropertyDef : object, System.ComponentModel.INotifyPropertyChanged
    {

        private object[] itemsField;

        private ItemsChoiceType[] itemsElementNameField;

        private string ifdguidField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Definition", typeof(string), Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute("DefinitionAliases", typeof(PropertyDefDefinitionAliases), Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute("Name", typeof(string), Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute("NameAliases", typeof(PropertyDefNameAliases), Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute("PropertyType", typeof(PropertyType), Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute("ValueDef", typeof(PropertyDefValueDef), Order = 0)]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
        public object[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
                this.RaisePropertyChanged("Items");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ItemsElementName", Order = 1)]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemsChoiceType[] ItemsElementName
        {
            get
            {
                return this.itemsElementNameField;
            }
            set
            {
                this.itemsElementNameField = value;
                this.RaisePropertyChanged("ItemsElementName");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ifdguid
        {
            get
            {
                return this.ifdguidField;
            }
            set
            {
                this.ifdguidField = value;
                this.RaisePropertyChanged("ifdguid");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class PropertyDefDefinitionAliases : object, System.ComponentModel.INotifyPropertyChanged
    {

        private PropertyDefDefinitionAliasesDefinitionAlias[] definitionAliasField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DefinitionAlias", Order = 0)]
        public PropertyDefDefinitionAliasesDefinitionAlias[] DefinitionAlias
        {
            get
            {
                return this.definitionAliasField;
            }
            set
            {
                this.definitionAliasField = value;
                this.RaisePropertyChanged("DefinitionAlias");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class PropertyDefDefinitionAliasesDefinitionAlias : object, System.ComponentModel.INotifyPropertyChanged
    {

        private string langField;

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string lang
        {
            get
            {
                return this.langField;
            }
            set
            {
                this.langField = value;
                this.RaisePropertyChanged("lang");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class PropertyDefNameAliases : object, System.ComponentModel.INotifyPropertyChanged
    {

        private PropertyDefNameAliasesNameAlias[] nameAliasField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("NameAlias", Order = 0)]
        public PropertyDefNameAliasesNameAlias[] NameAlias
        {
            get
            {
                return this.nameAliasField;
            }
            set
            {
                this.nameAliasField = value;
                this.RaisePropertyChanged("NameAlias");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class PropertyDefNameAliasesNameAlias : object, System.ComponentModel.INotifyPropertyChanged
    {

        private string langField;

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string lang
        {
            get
            {
                return this.langField;
            }
            set
            {
                this.langField = value;
                this.RaisePropertyChanged("lang");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class PropertyDefValueDef : object, System.ComponentModel.INotifyPropertyChanged
    {

        private object[] itemsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DefaultValue", typeof(PropertyDefValueDefDefaultValue), Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute("MaxValue", typeof(PropertyDefValueDefMaxValue), Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute("MinValue", typeof(PropertyDefValueDefMinValue), Order = 0)]
        public object[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
                this.RaisePropertyChanged("Items");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class PropertyDefValueDefDefaultValue : object, System.ComponentModel.INotifyPropertyChanged
    {

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class PropertyDefValueDefMaxValue : object, System.ComponentModel.INotifyPropertyChanged
    {

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class PropertyDefValueDefMinValue : object, System.ComponentModel.INotifyPropertyChanged
    {

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(IncludeInSchema = false)]
    public enum ItemsChoiceType
    {

        /// <remarks/>
        Definition,

        /// <remarks/>
        DefinitionAliases,

        /// <remarks/>
        Name,

        /// <remarks/>
        NameAliases,

        /// <remarks/>
        PropertyType,

        /// <remarks/>
        ValueDef,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class PropertyTypeTypePropertyBoundedValue : object, System.ComponentModel.INotifyPropertyChanged
    {

        private PropertyTypeTypePropertyBoundedValueValueRangeDef valueRangeDefField;

        private DataType dataTypeField;

        private UnitType unitTypeField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public PropertyTypeTypePropertyBoundedValueValueRangeDef ValueRangeDef
        {
            get
            {
                return this.valueRangeDefField;
            }
            set
            {
                this.valueRangeDefField = value;
                this.RaisePropertyChanged("ValueRangeDef");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public DataType DataType
        {
            get
            {
                return this.dataTypeField;
            }
            set
            {
                this.dataTypeField = value;
                this.RaisePropertyChanged("DataType");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public UnitType UnitType
        {
            get
            {
                return this.unitTypeField;
            }
            set
            {
                this.unitTypeField = value;
                this.RaisePropertyChanged("UnitType");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class PropertyTypeTypePropertyBoundedValueValueRangeDef : object, System.ComponentModel.INotifyPropertyChanged
    {

        private PropertyTypeTypePropertyBoundedValueValueRangeDefLowerBoundValue lowerBoundValueField;

        private PropertyTypeTypePropertyBoundedValueValueRangeDefUpperBoundValue upperBoundValueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public PropertyTypeTypePropertyBoundedValueValueRangeDefLowerBoundValue LowerBoundValue
        {
            get
            {
                return this.lowerBoundValueField;
            }
            set
            {
                this.lowerBoundValueField = value;
                this.RaisePropertyChanged("LowerBoundValue");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public PropertyTypeTypePropertyBoundedValueValueRangeDefUpperBoundValue UpperBoundValue
        {
            get
            {
                return this.upperBoundValueField;
            }
            set
            {
                this.upperBoundValueField = value;
                this.RaisePropertyChanged("UpperBoundValue");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class PropertyTypeTypePropertyBoundedValueValueRangeDefLowerBoundValue : object, System.ComponentModel.INotifyPropertyChanged
    {

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class PropertyTypeTypePropertyBoundedValueValueRangeDefUpperBoundValue : object, System.ComponentModel.INotifyPropertyChanged
    {

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class PropertyTypeTypePropertyEnumeratedValue : object, System.ComponentModel.INotifyPropertyChanged
    {

        private PropertyTypeTypePropertyEnumeratedValueEnumList enumListField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public PropertyTypeTypePropertyEnumeratedValueEnumList EnumList
        {
            get
            {
                return this.enumListField;
            }
            set
            {
                this.enumListField = value;
                this.RaisePropertyChanged("EnumList");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class PropertyTypeTypePropertyEnumeratedValueEnumList : object, System.ComponentModel.INotifyPropertyChanged
    {

        private string[] enumItemField;

        private string nameField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("EnumItem", Order = 0)]
        public string[] EnumItem
        {
            get
            {
                return this.enumItemField;
            }
            set
            {
                this.enumItemField = value;
                this.RaisePropertyChanged("EnumItem");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class PropertyTypeTypePropertyListValue : object, System.ComponentModel.INotifyPropertyChanged
    {

        private PropertyTypeTypePropertyListValueListValue listValueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public PropertyTypeTypePropertyListValueListValue ListValue
        {
            get
            {
                return this.listValueField;
            }
            set
            {
                this.listValueField = value;
                this.RaisePropertyChanged("ListValue");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class PropertyTypeTypePropertyListValueListValue : object, System.ComponentModel.INotifyPropertyChanged
    {

        private DataType dataTypeField;

        private UnitType unitTypeField;

        private Values valuesField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public DataType DataType
        {
            get
            {
                return this.dataTypeField;
            }
            set
            {
                this.dataTypeField = value;
                this.RaisePropertyChanged("DataType");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public UnitType UnitType
        {
            get
            {
                return this.unitTypeField;
            }
            set
            {
                this.unitTypeField = value;
                this.RaisePropertyChanged("UnitType");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public Values Values
        {
            get
            {
                return this.valuesField;
            }
            set
            {
                this.valuesField = value;
                this.RaisePropertyChanged("Values");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class PropertyTypeTypePropertyReferenceValue : ReferenceSelect
    {

        private DataType dataTypeField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public DataType DataType
        {
            get
            {
                return this.dataTypeField;
            }
            set
            {
                this.dataTypeField = value;
                this.RaisePropertyChanged("DataType");
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class PropertyTypeTypePropertySingleValue : object, System.ComponentModel.INotifyPropertyChanged
    {

        private DataType dataTypeField;

        private UnitType unitTypeField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public DataType DataType
        {
            get
            {
                return this.dataTypeField;
            }
            set
            {
                this.dataTypeField = value;
                this.RaisePropertyChanged("DataType");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public UnitType UnitType
        {
            get
            {
                return this.unitTypeField;
            }
            set
            {
                this.unitTypeField = value;
                this.RaisePropertyChanged("UnitType");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class PropertyTypeTypePropertyTableValue : object, System.ComponentModel.INotifyPropertyChanged
    {

        private string expressionField;

        private PropertyTypeTypePropertyTableValueDefiningValue definingValueField;

        private PropertyTypeTypePropertyTableValueDefinedValue definedValueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string Expression
        {
            get
            {
                return this.expressionField;
            }
            set
            {
                this.expressionField = value;
                this.RaisePropertyChanged("Expression");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public PropertyTypeTypePropertyTableValueDefiningValue DefiningValue
        {
            get
            {
                return this.definingValueField;
            }
            set
            {
                this.definingValueField = value;
                this.RaisePropertyChanged("DefiningValue");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public PropertyTypeTypePropertyTableValueDefinedValue DefinedValue
        {
            get
            {
                return this.definedValueField;
            }
            set
            {
                this.definedValueField = value;
                this.RaisePropertyChanged("DefinedValue");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class PropertyTypeTypePropertyTableValueDefiningValue : object, System.ComponentModel.INotifyPropertyChanged
    {

        private DataType dataTypeField;

        private UnitType unitTypeField;

        private Values valuesField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public DataType DataType
        {
            get
            {
                return this.dataTypeField;
            }
            set
            {
                this.dataTypeField = value;
                this.RaisePropertyChanged("DataType");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public UnitType UnitType
        {
            get
            {
                return this.unitTypeField;
            }
            set
            {
                this.unitTypeField = value;
                this.RaisePropertyChanged("UnitType");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public Values Values
        {
            get
            {
                return this.valuesField;
            }
            set
            {
                this.valuesField = value;
                this.RaisePropertyChanged("Values");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class PropertyTypeTypePropertyTableValueDefinedValue : object, System.ComponentModel.INotifyPropertyChanged
    {

        private DataType dataTypeField;

        private UnitType unitTypeField;

        private Values valuesField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public DataType DataType
        {
            get
            {
                return this.dataTypeField;
            }
            set
            {
                this.dataTypeField = value;
                this.RaisePropertyChanged("DataType");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public UnitType UnitType
        {
            get
            {
                return this.unitTypeField;
            }
            set
            {
                this.unitTypeField = value;
                this.RaisePropertyChanged("UnitType");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public Values Values
        {
            get
            {
                return this.valuesField;
            }
            set
            {
                this.valuesField = value;
                this.RaisePropertyChanged("Values");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class PropertySetDefPsetDefinitionAlias : object, System.ComponentModel.INotifyPropertyChanged
    {

        private string langField;

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string lang
        {
            get
            {
                return this.langField;
            }
            set
            {
                this.langField = value;
                this.RaisePropertyChanged("lang");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
}
